// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: data_transfer.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataTransferServiceClient is the client API for DataTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataTransferServiceClient interface {
	Transfer(ctx context.Context, in *DataTransferRequest, opts ...grpc.CallOption) (*DataTransferResponse, error)
}

type dataTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataTransferServiceClient(cc grpc.ClientConnInterface) DataTransferServiceClient {
	return &dataTransferServiceClient{cc}
}

func (c *dataTransferServiceClient) Transfer(ctx context.Context, in *DataTransferRequest, opts ...grpc.CallOption) (*DataTransferResponse, error) {
	out := new(DataTransferResponse)
	err := c.cc.Invoke(ctx, "/data_transfer.DataTransferService/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataTransferServiceServer is the server API for DataTransferService service.
// All implementations must embed UnimplementedDataTransferServiceServer
// for forward compatibility
type DataTransferServiceServer interface {
	Transfer(context.Context, *DataTransferRequest) (*DataTransferResponse, error)
	mustEmbedUnimplementedDataTransferServiceServer()
}

// UnimplementedDataTransferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataTransferServiceServer struct {
}

func (UnimplementedDataTransferServiceServer) Transfer(context.Context, *DataTransferRequest) (*DataTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedDataTransferServiceServer) mustEmbedUnimplementedDataTransferServiceServer() {}

// UnsafeDataTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataTransferServiceServer will
// result in compilation errors.
type UnsafeDataTransferServiceServer interface {
	mustEmbedUnimplementedDataTransferServiceServer()
}

func RegisterDataTransferServiceServer(s grpc.ServiceRegistrar, srv DataTransferServiceServer) {
	s.RegisterService(&DataTransferService_ServiceDesc, srv)
}

func _DataTransferService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataTransferServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data_transfer.DataTransferService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataTransferServiceServer).Transfer(ctx, req.(*DataTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataTransferService_ServiceDesc is the grpc.ServiceDesc for DataTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_transfer.DataTransferService",
	HandlerType: (*DataTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _DataTransferService_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_transfer.proto",
}
