// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: key_exchange.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKeyX int64 `protobuf:"varint,1,opt,name=public_key_x,json=publicKeyX,proto3" json:"public_key_x,omitempty"`
	PublicKeyY int64 `protobuf:"varint,2,opt,name=public_key_y,json=publicKeyY,proto3" json:"public_key_y,omitempty"`
}

func (x *KeyExchangeRequest) Reset() {
	*x = KeyExchangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeRequest) ProtoMessage() {}

func (x *KeyExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeRequest.ProtoReflect.Descriptor instead.
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *KeyExchangeRequest) GetPublicKeyX() int64 {
	if x != nil {
		return x.PublicKeyX
	}
	return 0
}

func (x *KeyExchangeRequest) GetPublicKeyY() int64 {
	if x != nil {
		return x.PublicKeyY
	}
	return 0
}

type KeyExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKeyX int64  `protobuf:"varint,1,opt,name=public_key_x,json=publicKeyX,proto3" json:"public_key_x,omitempty"`
	PublicKeyY int64  `protobuf:"varint,2,opt,name=public_key_y,json=publicKeyY,proto3" json:"public_key_y,omitempty"`
	Nonce      []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *KeyExchangeResponse) Reset() {
	*x = KeyExchangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_key_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeResponse) ProtoMessage() {}

func (x *KeyExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeResponse.ProtoReflect.Descriptor instead.
func (*KeyExchangeResponse) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *KeyExchangeResponse) GetPublicKeyX() int64 {
	if x != nil {
		return x.PublicKeyX
	}
	return 0
}

func (x *KeyExchangeResponse) GetPublicKeyY() int64 {
	if x != nil {
		return x.PublicKeyY
	}
	return 0
}

func (x *KeyExchangeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_key_exchange_proto protoreflect.FileDescriptor

var file_key_exchange_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x22, 0x58, 0x0a, 0x12, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x58, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x59, 0x22, 0x6f, 0x0a, 0x13,
	0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x58, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x59, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x32, 0x61, 0x0a,
	0x0b, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x52, 0x0a, 0x0b,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x2e, 0x6b, 0x65,
	0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4b, 0x65, 0x79, 0x45, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x6b, 0x65, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4b, 0x65, 0x79,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x65, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e,
	0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x38, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2d,
	0x72, 0x65, 0x70, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_key_exchange_proto_rawDescOnce sync.Once
	file_key_exchange_proto_rawDescData = file_key_exchange_proto_rawDesc
)

func file_key_exchange_proto_rawDescGZIP() []byte {
	file_key_exchange_proto_rawDescOnce.Do(func() {
		file_key_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_key_exchange_proto_rawDescData)
	})
	return file_key_exchange_proto_rawDescData
}

var file_key_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_key_exchange_proto_goTypes = []interface{}{
	(*KeyExchangeRequest)(nil),  // 0: key_exchange.KeyExchangeRequest
	(*KeyExchangeResponse)(nil), // 1: key_exchange.KeyExchangeResponse
}
var file_key_exchange_proto_depIdxs = []int32{
	0, // 0: key_exchange.KeyExchange.ExchangeKey:input_type -> key_exchange.KeyExchangeRequest
	1, // 1: key_exchange.KeyExchange.ExchangeKey:output_type -> key_exchange.KeyExchangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_exchange_proto_init() }
func file_key_exchange_proto_init() {
	if File_key_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_key_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyExchangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_key_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyExchangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_key_exchange_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_exchange_proto_goTypes,
		DependencyIndexes: file_key_exchange_proto_depIdxs,
		MessageInfos:      file_key_exchange_proto_msgTypes,
	}.Build()
	File_key_exchange_proto = out.File
	file_key_exchange_proto_rawDesc = nil
	file_key_exchange_proto_goTypes = nil
	file_key_exchange_proto_depIdxs = nil
}
